### ISSUE TITLE
Error: Failed to install add-on

### ISSUE THREAD

**Issue by Micro-Crackedto** [dut-iptv/dut-iptv.github.io#1]
Hello,

I am trying to install this add-on on LibreElec 9.2.1 [Kodi Leia v18.6] but it gives me an error regarding a dependency.
I do have Widevine installed.
Log: 
`2020-06-25 16:59:37.590 T:1799328640   ERROR: CAddonInstallJob[plugin.video.nlziet]: The dependency on script.module.fuzzywuzzy version 0.17.0 could not be satisfied.
`
Regards,

**Comment by dut-iptv** [comment]
I guess you tried to install one of the addons on its own instead of installing the repo?

Please install the repo using this [ZIP](https://github.com/dut-iptv/dut-iptv.github.io/raw/master/repository.anon.iptv-latest.zip) and then try installing the addon again.

Alternatively you can install fuzzywuzzy (for Leia) on its own using this [ZIP
](https://github.com/dut-iptv/dut-iptv.github.io/raw/master/leia/script.module.fuzzywuzzy/script.module.fuzzywuzzy-0.17.0.zip)

**Comment by Micro-Crackedto** [comment]
> I guess you tried to install one of the addons on its own instead of installing the repo?
> 
> 
> 
> Please install the repo using this [ZIP](https://github.com/dut-iptv/dut-iptv.github.io/raw/master/repository.anon.iptv-latest.zip) and then try installing the addon again.
> 
> 
> 
> Alternatively you can install fuzzywuzzy (for Leia) on its own using this [ZIP
> 
> ](https://github.com/dut-iptv/dut-iptv.github.io/raw/master/leia/script.module.fuzzywuzzy/script.module.fuzzywuzzy-0.17.0.zip)

Installing the Repo fixed it, thanks!
