### ISSUE TITLE
Old versions availability?

### ISSUE THREAD

**Issue by Nigel1992** [dut-iptv/dut-iptv.github.io#20]
Hi,

The older versions of the addon worked fine.
Could you reupload them to github ?

Do the addon use some external info that you update ?
Some settings or something
Because I keep getting new errors without doing anything.

**Comment by dut-iptv** [comment]
The background service does housekeeping in the background, updating the EPG for instance.
Because there is a major bug in the API (which is called by the brackground service) you keep getting errors.

Please disable the offending addons (Ziggo, Tmobile and NLziet are still to be fixed) in the meantime.
Fixes are in the works for all three remaining addons.

Older versions probably should be available as releases on this Github, but because of time restraints they have not been in the past and I will not be uploading them now. Because of changes to the EPG part they will not be of much use.

I will try to do better regarding releases/rollbacks/bugs etc. in the future but can and will make no promises.

**Comment by dut-iptv** [comment]
GitHub publishing script updated to automatically save older versions of the addon in the old directory
