### ISSUE TITLE
[Ziggo] Can’t watch live or replay tv

### ISSUE THREAD

**Issue by LarssW** [dut-iptv/dut-iptv.github.io#33]
When I want to watch replay or live tv I get an error saying:

![FCD8631C-7460-4A2C-90D1-53E440F10D71](https://user-images.githubusercontent.com/46047624/97488277-521a2f00-195e-11eb-9751-89334aab8095.jpeg)

**Comment by dut-iptv** [comment]
This unexpected error will be fixed in the next version.
The fix does not solve the underlying problem though.
The addon probably failed to login at ziggo.

What is the result when you input your user information again at "Change login information"
Do you get a message stating successful login or "Check user and pass"?

If so and if you are on a next box at home I suggest we continue the conversation about login problems with the new endpoint (next box users) in #30

**Comment by dut-iptv** [comment]
Error fixed in .110, but as stated previously it is probably a V3 login error (which is not fixed).

**Comment by LarssW** [comment]
Yes, you are right it has to do with new V3. I tried reauthenticating as suggested but it fails.

**Comment by dut-iptv** [comment]
Please try latest version

**Comment by LarssW** [comment]
Thanks, new update fixes the problem. Great work.

**Comment by dut-iptv** [comment]
Good to hear, closing
