### ISSUE TITLE
[NLZIET] NLZIET is reporting new login when this is not needed

### ISSUE THREAD

**Issue by jbouwh** [dut-iptv/dut-iptv.github.io#45]
The Kodi plugin seems not to reuse the authentication token. NL ziet service reports a new login each time this happens.

---
Succesvol ingelogd
Hallo J., Er is zojuist succesvol ingelogd op jouw NLZIET-account.

**Comment by Orbeatle** [comment]
Happens here as well.

**Comment by dut-iptv** [comment]
Will (probably) be fixed in the next version (no ETA)

**Comment by dut-iptv** [comment]
Please test in 116

**Comment by jbouwh** [comment]
Testing now with 116. The first time I started live TV a new login took place.
Now see what happens tomorrow.

**Comment by jbouwh** [comment]
Seems to be fixed in 116

**Comment by dut-iptv** [comment]
I still receive a lot of new login emails
I don't really have the time/energy to try to fix this permanently.

The current flow on the web login is very difficult to follow and reproduce.
The currently used app login style is difficult to debug/improve because I don't have access to the source and need to use MITM attacks and certificate spoofing on a rooted android device to even see anything that is going on.

I resorted to creating a rule in my email to automatically delete these mails

**Comment by jbouwh** [comment]
With version .116 this was solved, the error was reintroduced in the new version and exists in .141

**Comment by dut-iptv** [comment]
I don't think it was ever resolved, nothing has changed in the NLZiet login flow between 116 and 142. 

As stated in my previous posts: the NLZiet login flow is pretty convoluted and I don't consider it worth the substantial amount of time required to change the current flow.

You are free to create a pull request with a better login solution if you are willing and able to research this issue yourself.

Work around: Create an email rule to automatically delete the new login emails. Or ask NLZiet to create an option to disable the new login emails.

**Comment by jbouwh** [comment]
Ok, that is interesting. I waited testing and did not install any beta's. After you asked again at .116 I had no mails any more, but the pvr function stopped working. Do could in theory this pvr plugin could have caused relogin? It is happening once a day at most.

**Comment by dut-iptv** [comment]
The PVR plugin only downloads zip files from my GitHub repo that is used as an EPG storage.
It does not connect to any URL related to NLZiet.
All interaction with NLZiet is done by the NLZiet addon itself and only when you open some menu items, do a search or when you start a stream.

A possible explanation could be is that tokens are invalidated because they are not used every few hours because interaction with NLZiet is more limited now and that a new token is required to access NLZiet after the previous token is invalidated, which triggers a new login.

I might revisit recreating the OpenID login flow that is currently used by NLZiet on the website, but my previous attempt at this was unfruitful

**Comment by dut-iptv** [comment]
OAuth2 / Open ID Connect login flow that is currently used in the NLZiet webapplication was implemented in 148.
With proper refreshing off access_token using id_token (not requiring a new login)

After installing 148 you will get one more relogin mail and than they should stop.

148 currently available in the beta repo

@jbouwh Persistence pays off ;)

**Comment by jbouwh** [comment]
Testing .148 right now. I will monitor for a few days.

**Comment by jbouwh** [comment]
No relogin mail today. Looks good.

**Comment by jbouwh** [comment]
Looks solved, closing issue
