### ISSUE TITLE
[Ziggo] Archive playback no longer works

### ISSUE THREAD

**Issue by atreyuhere** [dut-iptv/dut-iptv.github.io#52]
Hi,

Archived programs can no longer be started from the guide or through the 'ask to play from beginning' option.
An error (Playback failed) is thrown or an addon error is visible onscreen (guide option).
Starting replay programs works from within the addon Replay TV section.
This occurs on the Leia and Matrix versions starting from version .116 

Regards,

A.

**Comment by dut-iptv** [comment]
By archived playback from the guide do you mean catchup using SimpleIPTV?

**Comment by atreyuhere** [comment]
Correct.
It used to work in earlier versions

**Comment by dut-iptv** [comment]
This bug was reproduced and fixed in 0.9.122 which is currently available in the beta repository.
The link between the addons and Simple IPTV have been moved to the "Dut-IPTV Simple IPTV Connector" addon.

If you want to keep using Simple IPTV to play content using my addons please update the addons you use to 0.9.122, re-login to your accounts and install the newly released addon "Dut-IPTV Simple IPTV Connector" and follow the setup wizard from the Program addons section of Kodi.

0.9.122 will probably be available in the main repository in a couple of days.

**Comment by atreyuhere** [comment]
I have followed your instructions to test from the beta repo.
Excellent work, first playround shows successful integration. Thank you for creating this !

**Comment by dut-iptv** [comment]
0.9.128 is available in the main repo and should fix this issue.

If you still encounter this or any other bug please post in #60.

Closing.
