### ISSUE TITLE
[Ziggo] Catchup is not working.. 

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv.github.io#57]
Hi, im using the latest version I could find. Version 0.9.119. Live tv is working fine, but as soon as Im trying to play a program in the past using the epg I'm getting this message:

![16099661681642685340339103525735](https://user-images.githubusercontent.com/2340835/103818586-1a6be980-5069-11eb-9fab-d40500bf4cb6.jpg)

Are there any specific settings I need to change before I can get this to work?

**Comment by dut-iptv** [comment]
Support for Simple IPTV has been removed from the main addons starting with 117.

There will be a seperate addon that handles integration of the addons and Simple IPTV but this addon is not finished at this time.

Live TV, Catchup and combining channels from multiple providers into one EPG will be supported.

Please wait for the release of the seperate addon or revert back to 115.

**Comment by powermarcel10** [comment]
That sounds promosing! Thanks for the info. If you need someone to test, let me know. I also have an iptv subscription, so I can test the multi provider feature.

**Comment by dut-iptv** [comment]
This bug was reproduced and fixed in 0.9.122 which is currently available in the beta repository.
The link between the addons and Simple IPTV have been moved to the "Dut-IPTV Simple IPTV Connector" addon.

If you want to keep using Simple IPTV to play content using my addons please update the addons you use to 0.9.122, re-login to your accounts and install the newly released addon "Dut-IPTV Simple IPTV Connector" and follow the setup wizard from the Program addons section of Kodi.

0.9.122 will probably be available in the main repository in a couple of days.

**Comment by powermarcel10** [comment]
Version 0.9.122 cannot be installed. It says Installation has failed. Version 0.9.123 can be installed but when I open it, even with a restart of kodi I'm getting this:

**Comment by dut-iptv** [comment]
This should be fixed in the latest version.

**Comment by dut-iptv** [comment]
0.9.128 is available in the main repo and should fix this issue.

If you still encounter this or any other bug please post in #60 .

Closing.
