### ISSUE TITLE
[NLZiet] Unexpected error when loading VOD 

### ISSUE THREAD

**Issue by freaktabnl** [dut-iptv/dut-iptv.github.io#58]
![image](https://user-images.githubusercontent.com/36622939/103871558-7c5e3a80-50cd-11eb-828e-f37cf5f9107a.png)

**Comment by freaktabnl** [comment]
Versie 09.115 werkt wel prima in Kodi Leia

**Comment by dut-iptv** [comment]
Pretty concise bug report....

Please post OS + version, Kodi version, addon version, action you were executing when you encountered etc. when posting an issue in the future.

Probably related to changes in retrieving VOD information and probably already fixed in 0.9.122 which is currently in the beta repository.

0.9.122 will probably be available in the main repository in a couple of days.

**Comment by dut-iptv** [comment]
0.9.128 is available in the main repo and should fix this issue.

If you still encounter this or any other bug please post in #59.

Closing.
